---
name: CalVer Release Action
description: Creates a new release using Calendar Versioning (CalVer) with format `YYYY.MM.PATCH`
author: Mircea-Pavel Anton

inputs:
  dry-run:
    description: 'Perform a dry run without creating an actual release'
    required: false
    default: 'false'
  draft:
    description: 'Create the release as a draft (unpublished).'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token with repository access'
    required: true

outputs:
  release-tag:
    description: 'The generated release tag (e.g., 2025.4.0)'
  previous-tag:
    description: 'The previous release tag that was used as reference'
  release-url:
    description: 'URL to the created GitHub release'

runs:
  using: 'node20'
  main: 'dist/index.js'
