---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  # ===============================================================================================
  actionlint:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-actionlint:latest@sha256:9c3cabe7afb8f89564dfbb70c46c823026ab8f1b1c501b0ad78f7985f87d93d2
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get changed files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: |-
            .github/workflows/**/*.yml
            .github/workflows/**/*.yaml

      - name: Run actionlint
        if: steps.changed-files.outputs.changed_files != '[]'
        run: actionlint

  commitlint:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-commitlint:latest@sha256:e81ffde72e02d663fd889a69c05ba6680c7a2bb2f7009a6b35f2f2bfc4aa9daa
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate PR commits with CommitLint
        run: echo "$PR_TITLE" | npx commitlint --extends=./.github/configs/commitlint.config.mjs
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

  markdownlint:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-markdownlint:latest@sha256:25087c8b7f992c20a9da4c97068185c9c7866543ff10c25fe92ca4eb974c737c
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get changed files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: |-
            .github/configs/.markdownlint.yaml
            **/*.md

      - name: Run MarkdownLint
        if: steps.changed-files.outputs.changed_files != '[]'
        run: markdownlint --config=.github/configs/.markdownlint.yaml "**/*.md"

  yamllint:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/gha-runner-yamllint:latest@sha256:5535a20fd0a8a35f5e2d245b55425df64b8fe02fdae8589fa57bb66b6b2e6999
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get changed files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: |-
            **/*.yml
            **/*.yaml

      - name: Run yamllint
        if: steps.changed-files.outputs.changed_files != '[]'
        run: yamllint --config-file=.github/configs/yamllint.yaml .
